name: Build and deploy the site
run-name: Publish site changes
on: 
  push:
    branches:
    - 'master'
jobs:
  Publish-Site:
    runs-on: ubuntu-latest
    steps:
      - name: "Instalar dependencias"
        run: sudo apt update && sudo apt install -y git yarn npm nodejs
      - name: "Setear secretos"
        env:
          DEPLOY_SECRET: ${{ secrets.SECRET }} 
        run: |
          mkdir -p ~/.ssh && 
          echo "$DEPLOY_SECRET" > ~/.ssh/id_rsa &&
          chmod 400 ~/.ssh/id_rsa && 
          cat ~/.ssh/id_rsa && 
          eval `ssh-agent -s` &&
          ssh-add ~/.ssh/id_rsa &&
          echo "Host *\\n\\tStrictHostKeyChecking no\\n\\n" > ~/.ssh/config
      - name: "Test"
        run: cat ~/.ssh/id_rsa
      - name: "Clonar repo origen" 
        run: git clone git@github.com:luiscruzv99/tramorea.git
      - name: "Clonar repo destino"
        run: git clone git@github.com:luiscruzv99/luiscruzv99.github.io.git
      - name: "Ir a repo de origen"
        run: cd tramorea
      - name: "Compilar proyecto"
        run: yarn install && yarn build
      - name: "Copiar artefactos"
        run: /bin/cp -rf build/* ../luiscruzv99.github.io/
      - name: "Ir a repo destino"
        run: cd ../luiscruzv99.github.io
      - name: "Preparar commit"
        run: git add *
      - name: "Comitear"
        run: git commit -m "${{ github.event.head_commit.message }}"
      - name: "Desplegar cambios"
        run: git push