name: Build and deploy the site
run-name: Publish site changes
on: 
  push:
    branches:
    - 'master'
jobs:
  Publish-Site:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: sudo apt update && sudo apt install -y git yarn npm nodejs
      - name: "Prepare environment"
        env:
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }} 
        run: |
          mkdir -p ~/.ssh && 
          echo "$DEPLOY_SECRET" > ~/.ssh/id_rsa &&
          chmod 400 ~/.ssh/id_rsa && 
          eval `ssh-agent -s` &&
          ssh-add ~/.ssh/id_rsa &&
          echo "Host *\\n\\tStrictHostKeyChecking no\\n\\n" > ~/.ssh/config
      - name: "Clone repo"
        run: cd .. && rm -rf tramorea && git clone git@github.com:luiscruzv99/tramorea.git
      - name: "Build site"
        run: yarn install && yarn build
      - name: "Clone site"
        run: cd .. && git clone git@github.com:luiscruzv99/luiscruzv99.github.io.git 
      - name: "Copy built artifacts"
        run: /bin/cp -rf build/* ../luiscruzv99.github.io/
      - name: "Deploy changes"
        run: |
          cd ../luiscruzv99.github.io &&
          git config user.email "luiscruzv99@gmail.com" &&
          git config user.name "Luis C" &&
          git add * &&
          git commit -m "${{ github.event.head_commit.message }}" &&
          git push